import type { RepoReport } from '../types';
import type { Analysis } from '../analysisTypes';

/** Build a shareable Markdown report from a finished analysis. */
export function reportToMarkdown(report: RepoReport): string {
  const analysis = report.analysis as Analysis | null;
  const name = report.url.replace('https://github.com/', '');
  const lines: string[] = [
    `# Beacon report — ${name}`,
    '',
    `> ${report.url} · analyzed ${new Date(report.created_at).toLocaleDateString()}`,
    '',
  ];

  if (analysis?.issues?.length) {
    lines.push('## Ranked issues', '');
    for (const i of [...analysis.issues].sort((a, b) => b.score - a.score)) {
      lines.push(`- **${i.score}/10** [#${i.number} ${i.title}](${i.github_url}) — _${i.difficulty}_`);
      lines.push(`  - ${i.reason}`);
    }
    lines.push('');
  }

  if (analysis?.architecture) {
    lines.push('## Architecture', '', analysis.architecture.summary, '');
    if (analysis.architecture.key_modules?.length) {
      lines.push('**Key modules:** ' + analysis.architecture.key_modules.map((m) => `\`${m}\``).join(', '), '');
    }
    const ownership = Object.entries(analysis.architecture.ownership ?? {});
    if (ownership.length) {
      lines.push('**Ownership:**', '');
      for (const [module, owners] of ownership) {
        lines.push(`- \`${module}\`: ${owners.map((o) => `@${o.replace('https://github.com/', '')}`).join(', ')}`);
      }
      lines.push('');
    }
  }

  if (analysis?.health) {
    const h = analysis.health;
    lines.push(
      '## Health', '',
      h.summary, '',
      `- Activity: ${h.activity}`,
      `- PR merge speed: ${h.pr_merge_speed}`,
      `- Contributor concentration: ${h.contributor_concentration}`,
      `- Trend: **${h.trend}**`,
      ''
    );
  }

  if (analysis?.starting_points?.length) {
    lines.push('## Start here', '');
    analysis.starting_points.forEach((p, i) => {
      lines.push(`${i + 1}. [${p.name}](${p.url}) — ${p.reason}`);
    });
    lines.push('');
  }

  lines.push('---', '_Generated by [Beacon](https://github.com/) — navigate open source like you\'ve been there before._');
  return lines.join('\n');
}

export function downloadMarkdown(report: RepoReport): void {
  const md = reportToMarkdown(report);
  const name = report.url.replace('https://github.com/', '').replace('/', '-');
  const blob = new Blob([md], { type: 'text/markdown' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `beacon-${name}.md`;
  a.click();
  URL.revokeObjectURL(url);
}
